### ISSUE TITLE
ユーザーのフォローとミュートが隣接している。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#13]
## どのような問題がありますか？
フォローとミュートという、真逆の操作が隣接しています。
（憶測ですが）誤った操作が発生するのではないでしょうか？
場所：フィード→投稿画像の右上「…」

## どうすれば良いですか？
ユーザーをミュートするを移動するのはどうでしょうか？

◆レイアウト案

（前略）
ユーザーをフォローする。
～～～～～～～～～～～～～～～～
ユーザーをミュートする。
ユーザーを通報する。
作品を通報する。

**Comment by haruharu-1105** [comment]
あとテストで、お題の投稿者のTOPの人を一件通報してしまいました。

**Comment by Stella2211** [comment]
自分も同意見だったので、プルリクを出しておきました。
