### ISSUE TITLE
通報機能について

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#14]
## どのテキストに関する問題ですか？

「通報」という文言が少し重いかなと思います。
・行っている行為はそうですが、私見ですが日常で「通報」という単語は余り使われないと思います。
・確認した所、Web側は、「報告」という単語を使用しています。

## どのように修正しますか？
「報告」という管理者に対処や判断を促す文言にするのはどうでしょうか？

※システム上で統一された単語があれば、そちらに統一でも。

**Comment by Stella2211** [comment]
こちら、内部的にも「報告」を使用していたので、「報告」に統一させていただきます。
