### ISSUE TITLE
バージョン情報をコピー時に端末情報もコピーしてほしい。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#19]
## どのような問題がありますか？
その他→バージョン情報をタップでコピーできますが、
Issuesを起票時に、バージョン情報と端末情報をコピーするのが手間です。
同時に情報をコピー出来ないでしょうか？

## どうすれば良いですか？
案）
App 0.2.0; Android 12; A202ZT Build/SP1A.210812.016

※アプリが落ち着いたら、不要かな思いますが。

**Comment by reiwa** [comment]
こちらのパッケージで情報を取得します。 https://pub.dev/packages/device_info_plus

**Comment by Stella2211** [comment]
実装しました。
iPadでも動作確認してみて、問題なさそうだったらマージします。
