### ISSUE TITLE
お題一覧

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#21]
## どのような問題がありますか？
１，下部のお題で未来の日付が表示される。本日は19日で、21日と20日分
結果、２件表示が減ります。

２，日付の下の欄に曜日を表示して欲しい。
すごく個人的な好みで申し訳ないのですが、週中や週末に一括でみるというシチュエーションがあります。
例）週中に「月曜日～水曜日」投稿分のお題イラストを見る。
このとき、曜日があると、タップしやすいです。

## どうすれば良いですか？
１，21日と20日の表示を消してほしい。

![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/9424d782-5128-49f6-b496-8faab3c6d09c)

２，曜日の表示に関して
１日　件数
(火)　お題　　イラスト

**Comment by Stella2211** [comment]
1についてはサーバー側の問題であるため、しぐれ煮さんに解決していただく必要があります。
2については自分も同意見なので、プルリクを出しておきました。

**Comment by haruharu-1105** [comment]
@Stella2211, @reiwa 
「１，下部のお題で未来の日付が表示される。`」
この件、解決して頂かなくても、問題ありません。

◯理由
未来のお題を確認する為に、利活用する方がいるのではないかと思いました。
前言撤回し申し訳ないのですが、慣れの問題だと思います。

issueをクローズします。
お時間を取って頂き、ありがとうございました。
