### ISSUE TITLE
フィード画面に、フォローボタンとシェアボタンが欲しい。

### ISSUE THREAD

**Issue by Stella2211** [aipictors/aipictors-flutter#22]
## どのような問題がありますか？
フォローとシェアはユーザーにもサイトにも有益な機能なのに、ミュートや通報と同じメニューの中にしかない。
## どうすれば良いですか？
下の画像のように、フィード画面にフォローボタンとシェアボタンを追加する。
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-19 at 20 38 39](https://github.com/aipictors/aipictors-flutter/assets/104188098/cf98c4d3-bdff-4825-9dd7-2d4b89f64fb1)

**Comment by haruharu-1105** [comment]
よい機能追加だと思います。
懸念事項として、フォロー解除の誤タップ操作が怖いです。

**Comment by Stella2211** [comment]
> フォロー解除の誤タップ操作が怖いです。

フォロー解除時に下記の確認ダイアログを表示するように変更しました。
![simulator_screenshot_DFF933D1-3679-4229-853B-5A04F7A77728](https://github.com/aipictors/aipictors-flutter/assets/104188098/43bb3166-4ccc-428d-b9a8-9566ba8684a6)
