### ISSUE TITLE
フィードのコメント欄の他言語対応

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#24]
## どのような問題がありますか？
フィードのコメント欄が、他言語でも「n件のコメント」と表示されている。

## どうすれば良いですか？
Twitterに倣って、💭n　表記に

※デメリット
コメント投稿画面に遷移したい時は、提案前の方が領域が大きいのでタップで遷移しやすい。

**Comment by Stella2211** [comment]
こちら、「n Comments」のように、今の文章自体を翻訳することも可能なのですが、どちらがよろしいでしょうか？
### アイコン
![cloud_comments](https://github.com/aipictors/aipictors-flutter/assets/104188098/5a1f5be6-d364-4415-b1ff-410bab2ced37)
### 文字
![n_comments](https://github.com/aipictors/aipictors-flutter/assets/104188098/98613370-89aa-4390-805a-8481ffed9295)

**Comment by haruharu-1105** [comment]
提案、ありがとうございます。
**文字でお願いします。**

理由は、タップ領域優先のため。
デメリットとしては、英語以外の他言語化対応時のコストかなと。

**Comment by Stella2211** [comment]
ありがとうございます！
文字で対応しました！
