### ISSUE TITLE
Twitterでログインの文言

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#32]
## どのテキストに関する問題ですか？

画面下部→ログイン画面
「Twitterでログイン」ボタン

## どのように修正しますか？
案１，「Twitter(X)でログイン」
　（個人的に一票）

案２、公式表記と統一するなら、「Xでログイン」
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/5866b6d0-783d-416b-82b0-a1bf12ae9935)

**Comment by Stella2211** [comment]
今はXであるという点と、今後Xという名前が普及していくだろうという点から、案1を元に、「X(Twitter)でログイン」に変更しました！
![signinwithtwitter](https://github.com/aipictors/aipictors-flutter/assets/104188098/0e26d864-f44b-44d9-ab6b-1f710faf1ba3)
