### ISSUE TITLE
利用規約やプライバシーポリシーの画面で右上にログインボタンが表示される。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#34]
## どのような問題がありますか？

・ログイン機能と勘違いします。
・画面に主題のコンテンツ（利用規約・プライバシーポリシー）と関係ない物が表示されるため、
　→個人的な違和感を覚えます。

## どうすれば良いですか？
非表示にしてほしいです。

**Comment by reiwa** [comment]
アプリ用の利用規約とプライバシーポリシーのページを作成して、後から切り替えます。

**Comment by haruharu-1105** [comment]
修正ありがとうございました。

利用規約とプライバシーポリシーのページが修正されたため、Closeします。
