### ISSUE TITLE
シェア作品をブラウザで表示時。「この接続はプライバシーが保護されません」の警告メッセージが表示

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#36]
## どの機能に関する不具合ですか？
- [ ] それ以外
シェア機能
（ブラウザ表示時なので、WEBサイト側）

## どのような不具合が発生しましたか？

シェアしたリンクをクリックしたときに、「この接続はプライバシーが保護されません」の警告メッセージが表示される。
Chrome
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/5b976ffc-b16f-4803-b7df-c1399f73dbba)

## どのような操作をしましたか？

1. 投稿作品をシェアボタン
1. Discrord（アプリ）→リンクをクリック→Chromeが起動する。
1. 不具合の内容が発生

## どの端末で確認しましたか？
- [ ] Android

## 許せないですか？
- [ ] 許せる

【参考】シェア機能で使用した投稿作品
`check out! https://aipictors.com/works/93365`

**Comment by Stella2211** [comment]
こちら、mainブランチでは4時間前に[修正した](https://github.com/aipictors/aipictors-flutter/commit/b35e6b8d6c4b0bd20f0e804d1bbf11b4489dd0a0)ので、アプリの更新待ちです。

**Comment by nakatsuka-k** [comment]
DNS側の問題で現在はこのようなエラーが出なくなりました。
