### ISSUE TITLE
【多言語化】お題タブ

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#41]
## どのような問題がありますか？
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/ed79a050-4e90-4383-aa0b-7b1f19b5f822)

1. 年月部　例)2023年8月
1. 日付部　例)21日と今日
1. 件数部　例)0件
1. お題部　例)噴水

## どうすれば良いですか？
日付表記をどう扱い、どう対応するかのは方針決定が必要だと思われます。

**Comment by Stella2211** [comment]
1. 8/2023のように、{month}/{year}で表記。
2. 21のように数字のみにし、今日はTodayに。
3. n Works。
4. 一旦保留。

上記でいかがでしょうか？

**Comment by haruharu-1105** [comment]
返信ありがとうございます。修正案は、すごくいいと思います。

日付のサーバー側のタイムゾーンはどこでしょうか？
日本標準時 (JST)でしょうか？その場合、現地の時間と時差が発生しますが問題ありませんか？

**Comment by Stella2211** [comment]
確かに、お題にはその問題がありそうです。
具体的には、外国からのアクセス時に、Todayの次の日の投稿が表示されることと、その日のお題の切り替わるタイミングが、外国のユーザーにとっては謎な時間になることでしょうか。
これらは解消が難しそうなので、とりあえずこのままにしておきます。
他の部分については、基本的にユーザーのタイムゾーンに合わせた時刻を表示するようになっているので、多分問題ないです。

**Comment by Stella2211** [comment]
画像のように実装しました。
月表示の部分について、これをアルファベットで表示するためには、言語ごとに処理を分けなければならず、複雑になってしまうため、とりあえず数字で実装しました。何か問題があるようでしたら、アルファベット表示を実装します。
![simulator_screenshot_25A6909B-480E-458D-AC2D-B023C9BC3C4F](https://github.com/aipictors/aipictors-flutter/assets/104188098/bcef48a6-b812-4dbd-a493-c251c31ae37c)

**Comment by haruharu-1105** [comment]
了解です。対応ありがとうございました。
