### ISSUE TITLE
LOVEスタンプが表示されない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#46]
## どの機能に関する不具合ですか？

- [ ] フィード

## どのような不具合が発生しましたか？

コメント表示で、LOVEスタンプが表示されない。
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/32bb9581-87da-4cb8-b697-786faa3c6a3b)
（不具合が発生してるのは、Adminのコメント欄です。

## どのような操作をしましたか？

1. フィードでお題（8月21日）をタップ
1. 「みなさま。おはようございます。」の作品をタップ。

作品ID
https://www.aipictors.com/works/96659/
## どの端末で確認しましたか？
- [ ] Android

## 許せないですか？
- [ ] 許せる
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/1291777d-b74d-4da7-8b0d-0f5dea45187f)

**Comment by Stella2211** [comment]
他のスタンプも、一部見られないものがありそうです。
自分の作品ページでは、「Thank You」スタンプが表示されないことを確認できました。
以前、Web版でも同様の問題が発生していたので、サーバー側のバグかなと思います。

**Comment by Stella2211** [comment]
修正されたようです。
![admin_love](https://github.com/aipictors/aipictors-flutter/assets/104188098/441bf992-dc4d-46c8-9f6e-2a87ff3149b5)
