### ISSUE TITLE
【多言語化】フィードのお題タブ

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#47]
## どのような問題がありますか？

1. 今日のお題欄　「今日のテーマは「噴水」だよ！」
1. お題の作品投稿欄　「＋お題の作品」

## どうすれば良いですか？
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/f26e2a09-e35b-4adf-9714-01e723283745)
1. Today's theme is "$title"
1. ＋ Today's Theme .

1のサーバー側の$title部に関しては、保留し検討事項に。
https://github.com/aipictors/aipictors-flutter/blob/8224f5297289a3c5914642369e15b5663a6f7908/lib/widgets/list_tile/daily_theme_title_list_tile.dart#L20

**Comment by Stella2211** [comment]
ありがとうございます！
おっしゃる通りに実装させていただきました！
![simulator_screenshot_7CE5CB1D-0EB3-4247-9CA0-9949384CA88A](https://github.com/aipictors/aipictors-flutter/assets/104188098/e4d162f5-bc0a-4a86-8bf1-05624a273a2d)
