### ISSUE TITLE
【他言語化】作品の報告機能

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#48]
## どのような問題がありますか？
1. 作品をシェアする欄
1. ユーザーをフォローする欄
1. ユーザーをミュートする欄
1. ユーザーを通報する欄
1. 作品を通報する欄
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/bc42a517-576a-4ab1-bb3c-73cfa8077d6c)

## どうすれば良いですか？
1. Work Share.
1. User Follow.
1. User Mute.
1. User Report.
1. Work Report.
1は、プロフィール画面には、「ユーザーをシェアする」機能があるため、区別するためにWork を追加しました。
【参考】Redditの場合です。
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/fec39f44-6a2e-453c-a16c-cf97a21d0119)

※別件です
assetsの重複投稿画像の削除をお願い致します。
https://github.com/aipictors/aipictors-flutter/assets/132221228/94fdfc72-50ac-4a35-bc62-e358e1bbc4f4

**Comment by Stella2211** [comment]
ありがとうございます！
翻訳についてなのですが、個人的には「Work Share」よりも、「Share Work」の方がより適切かなと思いました。

また、重複投稿画像の削除についてなのですが、こちらからは難しそうです。
もしも問題があるようでしたら、下記の記事を参考に、Github Supportに問い合わせていただいた方がいいかもしれません。
https://tech.coincheck.blog/entry/2022/10/21/113906

**Comment by haruharu-1105** [comment]
ありがとうございます。
「Share Work」の場合ですと。ユーザーをシェアする「Share User」でしょうか？
残りの翻訳はどう致しましょう。
User Follow.
User Mute.
User Report.
Work Report.

**Comment by Stella2211** [comment]
Follow User
Mute User
Report User
Report Works
でいかがでしょうか。

**Comment by haruharu-1105** [comment]
いいと思います。統一的な翻訳仕様なので、Disscationに纏めますね。

**Comment by Stella2211** [comment]
ありがとうございます！
あ、「Report Works」ではなく、「Report Work」でした、ごめんなさい🙇

**Comment by Stella2211** [comment]
画像のように実装させていただきました！
![menu](https://github.com/aipictors/aipictors-flutter/assets/104188098/04ae5c22-6af9-4bb9-8184-4b7c84e1bcab)
