### ISSUE TITLE
【多言語化】プロフィールの作品欄

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#50]
## どのような問題がありますか？
1. 作品欄
1. フォローする欄
1. コメント欄
1. タイトル欄
1. キャプション欄
1. タグ欄
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/00ec7439-cc59-41ba-b37b-f9cd88245ce7)
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/1967dea7-0582-408a-8f34-8cdcb8059a29)

## どうすれば良いですか？
1. Work
1. Follow User
1. Comments
1. タイトル欄　英語タイトルがあれば、Translated text + 改行 + 英語タイトルを表示
1. キャプション欄　英語キャプションがあれば、英語キャプションを表示
1. タグ欄

1はフィードのLatest Worksに合わせて、
https://github.com/aipictors/aipictors-flutter/blob/main/assets/i18n.json
3と4は、暫定案です。
理由は、自動翻訳を意識している方が少ないと思われるので、一括確認事項でしょうか。

【参考】 Skebの場合（投稿画像と一切関係ありません）は、翻訳文の場合Translated textを太文字に付与
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/d85f54d2-c799-4730-b9ca-4fecc4eb945f)

**Comment by Stella2211** [comment]
1,3は実装しました！
2については、日本語が「フォローする」だけなので、「Follow」としておきました！
4,5は可能であれば実装したかったのですが、GraphQLサーバーからのレスポンスに英語のデータがないので、実装できませんでした。
![simulator_screenshot_7A348BF0-A002-4F11-9D1C-2202559C029B](https://github.com/aipictors/aipictors-flutter/assets/104188098/b5f2f12b-ea09-4c5c-9806-b1f98b90e114)
