### ISSUE TITLE
作品画面下部のハートアイコン、ブックマークアイコンの動作について

### ISSUE THREAD

**Issue by animel7316** [aipictors/aipictors-flutter#53]
## どの機能に関する不具合ですか？

- [x] フィード

## どのような不具合が発生しましたか？

- ブックマークアイコンがデフォルトでタップ済みの状態となっている
- ハートアイコンをタップすると、一度ブックマークのタップ済みが解除され、その後再度タップ済みの状態となる

## どのような操作をしましたか？

1. フィードから作品画面へ遷移
2. 作品画面下部のハートアイコンをタップする

## どの端末で確認しましたか？

- [ ] iOS
- [x] Android

## 許せないですか？

- [x] 許せない
デフォルトの表示条件が誤っている可能性がありますので、ご確認いただければと思います。

**Comment by Stella2211** [comment]
ご報告ありがとうございます！
ハートアイコンと同じ変数を使用しているというバグがありました。
また、新たに発覚した問題として、現在のブックマークボタンは動作していないようです。
ご不便をおかけしてしまい申し訳ありません。
