### ISSUE TITLE
フォロー通知の内容がブラウザと一致しない

### ISSUE THREAD

**Issue by erot-ai** [aipictors/aipictors-flutter#54]
## どの機能に関する不具合ですか？

- [x] #57

## どのような不具合が発生しましたか？

通知リストのフォロー通知について、ブラウザのものと比較すると

- 別のユーザにフォローされたことになっている
- 「この通知は削除されました」となっている

| ブラウザ | アプリ |
| --- | --- |
| ![](https://github.com/aipictors/aipictors-flutter/assets/138782531/728a0460-f2bd-4e67-9136-8478b75ea9d8) | ![](https://github.com/aipictors/aipictors-flutter/assets/138782531/ddc9a4d4-1d11-4594-9363-68239a616396) |
| ![](https://github.com/aipictors/aipictors-flutter/assets/138782531/8d7e8066-933e-4f2b-9739-d32a948995e3) | ![](https://github.com/aipictors/aipictors-flutter/assets/138782531/e20e0168-30b4-4347-9be0-54cf332048a4) |

## どのような操作をしましたか？

1. 通知タブを表示

## どの端末で確認しましたか？

- [x] Android

## 許せないですか？

- [x] 許せない

**Comment by Stella2211** [comment]
ご不便をおかけし申し訳ありません。
私の環境でも同じ問題が起きているようです。
現在調査中なので、しばらくお待ちください。

**Comment by reiwa** [comment]
システムの方の不具合です。対応しました。
