### ISSUE TITLE
キーワードを変えずに検索時に、クリアアイコンが戻らない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#58]
## どの機能に関する不具合ですか？

- [x] それ以外
　キーワード検索
## どのような不具合が発生しましたか？

下記操作後に、キーワード検索欄の右側にあるバツマークのアイコンが「歯車」アイコンのままです。
※アイコン表示の問題で、タップすればクリアはされます。

## どのような操作をしましたか？

1. 「ひつじ」でキーワード検索
1. 右上の✗（バツマーク）をタップ
1. 検索欄をタップし、キーワードを変えずに再度検索

## どの端末で確認しましたか？

- [x] Android

## 許せないですか？

- [x] 許せる

**Comment by Stella2211** [comment]
検索結果表示画面のバツボタンが正しく動作していなかったことが原因のようです。修正させていただきました。
