### ISSUE TITLE
文章のみのコメントの場合、削除スタンプが表示される。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#69]
## どの機能に関する不具合ですか？
- [x] それ以外　作品画面
　　
## どのような不具合が発生しましたか？

文章のみのコメントの場合、DELETED STAMPが表示される。

## どのような操作をしましたか？

1. 見つける→キーワード検索「海と少女」
1. 最初にHITする。Stellaさんの作品(96295)を表示

## どの端末で確認しましたか？
- [x] Android

## 許せないですか？
- [x] 許せる
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/37de64ca-e768-462e-8394-fbc05a276283)

◆謝辞
Special thanks to Stella.

**Comment by Stella2211** [comment]
こちら、修正されたようです。
![simulator_screenshot_951190A0-9A55-457F-B7E6-749AFFE6ACA7](https://github.com/aipictors/aipictors-flutter/assets/104188098/8e6220a4-3d4f-4d36-b874-c3e811f6657f)
