### ISSUE TITLE
【多言語化】その他のアカウント画面 

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#70]
## どのような問題がありますか？
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/1df14d17-e284-4367-a578-7d727cc06dc5)
1. ログインIDの変更
1. ログインに使用するIDを変更します。
1. パスワードの変更
1. ログインに使用するパスワードを変更します。
1. アカウントの削除
## どうすれば良いですか？
1. Change Sign in ID.
1. Change the ID used for sign in.
1. Change your password.
1. Change the password used for sign in.
1. Delete Account.
1. Delete the currently signed-in account.

## 関連
#45

**Comment by Stella2211** [comment]
ありがとうございます！実装させていただきました！
![others_account_screen](https://github.com/aipictors/aipictors-flutter/assets/104188098/4f0ab192-6600-44d2-aedd-f6ff3ad8c1ac)
