### ISSUE TITLE
画像のポップアップ表示を閉じる方法を変更する

### ISSUE THREAD

**Issue by Stella2211** [aipictors/aipictors-flutter#78]
## どのような問題がありますか？
現在フィード画面には、画像をタップして拡大表示できる機能があります。
この機能は便利なのですが、添付動画のように、簡単にポップアップが閉じてしまうため、あまり操作性がよくないです。
この原因は、閉じる操作が上下のスワイプに設定されているからです。

[現在の動作.webm](https://github.com/aipictors/aipictors-flutter/assets/104188098/d5d0e62b-d4c5-4033-a9dc-07234c70742d)

## どうすれば良いですか？
閉じる動作を変更する。
現在の上下スワイプではなく、画像をタップに変更する。
これにより、より直感的に操作できるようになる上に、誤って閉じてしまうことが減ります。
下記が動作を変更した場合の動画です。

[変更後の動作.webm](https://github.com/aipictors/aipictors-flutter/assets/104188098/e6e47b19-447d-4546-b4fc-030a9acbb020)

**Comment by Stella2211** [comment]
自分のイラストで検証動画を撮影するため、作品画面にも同じ機能を追加しました。
動作はフィード画面と全く同じです。

**Comment by haruharu-1105** [comment]
個人的には、申し訳ないのですが反対です。
理由は、大手の他サイトと動きが合わないため、誤操作（閉じる操作を上下スワイプで行ってしまう）が発生する可能性があるからです。
（データを取らないと分かりませんが）

調査した所、拡大はタップで共通でした。

| サイト | 閉じるボタン | 詳細表示/縮小 |詳細表示で拡大縮小 |
| :--- | :---: | :---:  | :---: |
| twitter | 左上 または 上下スワイプ | ダブルタップ | ピンチイン |
| discord | 左上 または 上下スワイプ | ダブルタップ | ピンチイン |
| pixiv(WEB) | 左上 | ダブルタップ※ズームのみ | - | ピンチイン |

別件ですが、名札がkawaiiですね。

**Comment by Stella2211** [comment]
ありがとうございます！
自分はとにかく誤って閉じることを減らしたいので、その方法は何でも構いません！
実際の動作を確認してみたところ、TwitterとDiscordでは、画像をズームしていない状態で上下スワイプすると閉じられるようです。
今のアプリは、ズームしていても閉じてしまうので、可能であれば、TwitterとDiscordの動きに合わせたいと思います。
なにか他にいい方法はありますでしょうか？

**Comment by haruharu-1105** [comment]
TwitterとDiscordの動きに合わせて、以下の仕様はどうでしょうか？

- タップ後の拡大の初期サイズ以外は、上下スワイプで閉じないようにする。
- 拡大後の画面は、ダブルタップでトグル（拡大原寸/詳細拡大)する。
- 左上に閉じるボタンを追加する。
（ピンチイン/ピンチアウト時のショートカット）

**Comment by Stella2211** [comment]
いいと思います！
