### ISSUE TITLE
メンテ中は、お知らせ欄が表示されない。

### ISSUE THREAD

**Issue by haruharu-1105** [aipictors/aipictors-flutter#79]
## どのような問題がありますか？
私の勘違いだったら申し訳ないのですが、
メンテ中、「お知らせ」欄（フィードのフォロー欄上部）が表示されません。
そのため、メンテナンス状況が分からないです。

## どうすれば良いですか？
致命度にもよりますが、「メンテナンス中です、公式サイトのお知らせを確認ください」等を表示して頂けると嬉しいです。

添付ファイルは、メンテ状態の時のアプリ表示です。
![image](https://github.com/aipictors/aipictors-flutter/assets/132221228/da598c6e-d736-4bbe-a304-0ddc32703194)

**Comment by reiwa** [comment]
メンテナンスモード機能を追加する。既に変数があるのでページを追加する。

![Screenshot 2023-08-31 at 3 21 04](https://github.com/aipictors/aipictors-flutter/assets/8127869/df548ec7-447e-4715-a95e-7ea845777cc3)

**Comment by reiwa** [comment]
ページを追加した。
